source: artifacts.lan.tribe29.com:4000/ubuntu-20.04:sandbox-timotheus.bachinger-mapy311-latest
tag: artifacts.lan.tribe29.com:4000/ubuntu-20.04:sandbox-timotheus.bachinger-mapy311-2023.01.17-53301b796ef
