[project]
name = "cmk-trace"
version = "1.0.0"
dynamic = ["dependencies"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.package-data]
"cmk.trace" = ["py.typed"]

[tool.bandit]

[tool.ruff]
target-version = "py312"
line-length = 100

[tool.ruff.lint.isort]
order-by-type = false

[tool.ruff.lint]
select = ["E", "F", "I", "W", "C90", "PL", "RUF100"]
ignore = [
  # Ignore findings which are incompatible with our "import" techonology.
  "F401", # 'FOO' imported but unused
  "E402", # module level import not at top of file
  "F403", # 'from FOO import *' used; unable to detect undefined names
  "F405", # 'FOO' may be undefined, or defined from star imports: BAR
  # We should probably have a look at these findings.
  "E731", # do not assign a lambda expression, use a def
  "E741", # ambiguous variable name 'FOO'
  # pylint doesn't complain about these
  "PLC0414", # Import alias does not rename original package
  "PLR0911", # Too many return statements
  "PLR0912", # Too many branches
  "PLR0913", # Too many arguments in function definition
  "PLR0915", # Too many statements
  "PLR2004", # Magic value used in comparison, consider replacing `FOO` with a constant variable
  "PLR2044", # Line with empty comment
  "PLW0603", # Using the global statement to update `FOO` is discouraged
  "PLW2901", # `for` loop variable `FOO` overwritten by assignment target
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["cmk", "tests"]
addopts = "--doctest-modules --import-mode=importlib"
