[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cmk_graphing"
version = "1.0.0"

[tool.isort]
# configuration options compatible with black
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
ensure_newline_before_comments = "True"
order_by_type = "False"
line_length = 100

[tool.black]
line-length = 100

[tool.mypy]
strict = true

[tool.pylint]
disable = "missing-docstring,line-too-long"

# We need this section, even if it is empty, without it pytest won't consider
# our package directory as the root directory and climbs up further, see:
# https://docs.pytest.org/en/stable/reference/customize.html#finding-the-rootdir
[tool.pytest.ini_options]
