[project]
name = "cmk-agent-based"
version = "1.0.0"
dynamic = ["dependencies"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.package-data]
"cmk.agent_based" = ["py.typed"]

[tool.bandit]

[tool.ruff]
target-version = "py312"
line-length = 100

[tool.ruff.lint]
# (not yet) implemented pylint rules under ruff (by the time writting...):
# | too-many-instance-attributes rule (R0902)
# | too-many-function-args            (E1121)
# | duplicate-code                    (R0801)
select = ["A", "ARG", "E", "F", "W", "C90", "PL", "RUF100", "SLF"]
ignore = [
  "PLR2004", # Magic value used in comparison, consider replacing `FOO` with a constant variable
]

[tool.ruff.lint.per-file-ignores]
# Explicit re-exports is fine in __init__.py, still a code smell elsewhere.
"__init__.py" = ["PLC0414"]

#[tool.ruff.lint.isort]
# see ruff.toml for the isort section

# [tool.mypy]
# Configure under the corresponding [[tool.mypy.overrides]] array
# in the root `pyproject.toml`.

[tool.pytest.ini_options]
consider_namespace_packages = true
testpaths = ["tests"]
