[project]
name = "cmk-shared-typing"
version = "1.0.0"
dynamic = ["dependencies"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.package-data]
"cmk.werks" = ["py.typed"]

[tool.bandit]

[tool.ruff]
target-version = "py312"
line-length = 100

[tool.ruff.lint.isort]
order-by-type = false

[tool.pylint.format]
max-line-length = 100
persistent = "no"
score = "no"

[tool.pylint.messages_control]
disable = "missing-docstring,fixme"

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["cmk", "tests"]
addopts = "--doctest-modules --import-mode=importlib"
