---
- name: hello world
  hosts: 127.0.0.1
  connection: local

  vars:
    checkmk_server_sites:
      - name: cmk
        version: "{{ checkmk_server_version }}"
        state: started
        admin_pw: cmk


  roles:
    - tribe29.checkmk.server

  tasks:
    - name: enforce password change
      copy:
        dest: "/omd/sites/{{ item.name }}/var/check_mk/web/cmkadmin/enforce_pw_change.mk"
        content: 1
        owner: cmk
        group: cmk
      become: true
      loop: "{{ checkmk_server_sites }}"
