[package]
name = "check_http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = { version = "*", features = ["aes", "std"] }
anyhow = { version = "*" }
clap = { version = "4.3.19", features = ["derive"] }
http = "0.2.9"
reqwest = { version = "0.11.18", features = ["json"] }
scrypt = { version = "*", default-features = false, features = ["std"] }
tokio = { version = "1.29.1", features = ["full"] }
