[package]
name = "check_http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = { version = "*", features = ["aes", "std"] }
anyhow = { version = "*" }
clap = { version = "*", features = ["derive"] }
http = { version = "*" }
reqwest = { version = "*", features = ["json"] }
scrypt = { version = "*", default-features = false, features = ["std"] }
tokio = { version = "*", features = ["full"] }
openssl = { version = "*", features = ["vendored"] }
